CREATE TABLE IF NOT EXISTS {{APP_USERS_TABLE}} (
  id STRING NOT NULL,
  username STRING NOT NULL,
  password_hash STRING NOT NULL,
  created_at TIMESTAMP NOT NULL,
  updated_at TIMESTAMP NOT NULL
) USING DELTA
